name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./coachme-frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./coachme-frontend

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./coachme-frontend